---
title: "Facet Graph"
output: github_document
---

_author_: **[Niccolò Salvini](https://niccolosalvini.netlify.app/)**
_date_: `r format(Sys.Date(), "%d %B, %Y")`





```{r global.options, include=FALSE, message=FALSE}

knitr::opts_chunk$set(
  warning = FALSE,  
  strip.white = TRUE,
  fig.path = "imgOut/", 
  fig.width=12,
  fig.height=8,
  cache = FALSE
)
source("libs.R")

knitr::knit_hooks$set(imgcenter = function(before, options, envir){  # to center image 
  if (before) {                                                      # add imgcenter = TRUE
    htmltools::HTML("<p align='center'>")                            # to the chunk options
  } else {
    htmltools::HTML("</p>")
  }
}
)

theme_nicco = function (base_size = 11, base_family = "") {
    theme_bw() %+replace% 
    theme(
      text = element_text(family = "sans", size = 12),
      plot.title = element_text(face = "bold", size = 14, margin=margin(0,0,30,0)),
      panel.background  = element_blank(),
      axis.ticks = element_line(colour = "grey70", size = 0.2),
      plot.background = element_rect(fill="white", colour=NA),
      legend.background = element_rect(fill="transparent", colour=NA),
      legend.key = element_rect(fill="transparent", colour=NA)
    )
}

```


```{r load_data, echo=FALSE, message=FALSE}

library(readr)

dataset = read_delim("data/final_dataset.csv", 
    ";", escape_double = FALSE, col_types = cols(X1 = col_skip(), 
        floor = col_factor(levels = c("0", 
            "1", "2", "3", "4", "5", "6", 
            "7", "8", "9", "10", "11", "12"))), 
    trim_ws = TRUE)

```

```{r Facetted_Graph}

ldataset = dataset %>%
  dplyr::filter(price >= 500L & price <= 5047L) %>%
  dplyr::filter(condom >= 0L & condom <= 1030L) %>%
  dplyr::filter(!(floor %in% c("NA", "12", "10")))

q = ggplot(ldataset) +
  aes(x = price, y = condom, colour = condom, size = condom) +
  geom_point() +
  scale_color_gradient() +
  theme_minimal() +
  facet_wrap(vars(nroom), scales = "free_x") +
  ggtitle("Facetted_Graph bubbled for nrooms") +
  theme_nicco()
q

```

